export default {
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

    FETCH_ORG_REQUEST: 'FETCH_ORG_REQUEST',
    FETCH_ORG_SUCCESS: 'FETCH_ORG_SUCCESS',
    FETCH_ORG_FAILURE: 'FETCH_ORG_FAILURE',

    FETCH_EVENT_REQUEST: 'FETCH_EVENT_REQUEST',
    FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
    FETCH_EVENT_FAILURE: 'FETCH_EVENT_FAILURE'
};