export default {
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

    FETCH_ORG_REQUEST: 'FETCH_ORG_REQUEST',
    FETCH_ORG_SUCCESS: 'FETCH_ORG_SUCCESS',
    FETCH_ORG_FAILURE: 'FETCH_ORG_FAILURE',

    FETCH_ORGS_REQUEST: 'FETCH_ORGS_REQUEST',
    FETCH_ORGS_SUCCESS: 'FETCH_ORGS_SUCCESS',
    FETCH_ORGS_FAILURE: 'FETCH_ORGS_FAILURE',

    FETCH_EVENT_REQUEST: 'FETCH_EVENT_REQUEST',
    FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
    FETCH_EVENT_FAILURE: 'FETCH_EVENT_FAILURE',

    FETCH_EVENTS_REQUEST: 'FETCH_EVENTS_REQUEST',
    FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FETCH_EVENTS_FAILURE: 'FETCH_EVENTS_FAILURE'
};